databases:
  - name: yosan-db
    plan: free
    ipAllowList: []

services:
  - type: web
    name: yosan-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT wsgi:application
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: yosan-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true 