"""Add payment_date and notes to Payment model

Revision ID: 0fc398c52483
Revises: d6c36ae44f84
Create Date: 2025-02-08 01:00:20.251458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fc398c52483'
down_revision = 'd6c36ae44f84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('payment_date')

    # ### end Alembic commands ###
