"""Add is_profit column to Payment model

Revision ID: 62ec517a17b1
Revises: e72bf4f951c5
Create Date: 2025-02-24 15:48:05.597373

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62ec517a17b1'
down_revision = 'e72bf4f951c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_profit', sa.Boolean(), nullable=True))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('current_budget')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_budget', mysql.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('is_profit')

    # ### end Alembic commands ###
