"""add payment model

Revision ID: 9746611f2204
Revises: ce380581ad18
Create Date: 2025-03-12 17:10:21.639237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9746611f2204'
down_revision = 'ce380581ad18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('construction_budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remaining_amount', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('construction_budget', schema=None) as batch_op:
        batch_op.drop_column('remaining_amount')

    # ### end Alembic commands ###
