"""Add target management rate to Project model

Revision ID: d941946cbf86
Revises: 62ec517a17b1
Create Date: 2025-02-24 16:47:18.954211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd941946cbf86'
down_revision = '62ec517a17b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_management_rate', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('target_management_rate')

    # ### end Alembic commands ###
