"""Add payment_date column to payments table

Revision ID: xxxxxxxxxxxx
Revises: previous_revision_id
Create Date: yyyy-mm-dd hh:mm:ss.ssssss

"""
from alembic import op
import sqlalchemy as sa

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'payment_date')
    # ### end Alembic commands ### 